-- 기도로 짓는 집 — Supabase fallback
create table if not exists public.prayer_hours (
  id bigint generated by default as identity primary key,
  topic text not null,
  heart text,
  hours numeric(6,2) not null check (hours > 0 and hours <= 100),
  name text,
  ts timestamptz not null default now()
);

alter table public.prayer_hours enable row level security;

drop policy if exists "public insert prayer" on public.prayer_hours;
create policy "public insert prayer"
on public.prayer_hours for insert
to anon
with check (hours > 0 and hours <= 100 and length(topic) <= 500 and length(coalesce(name,'')) <= 30);

drop policy if exists "public read hours" on public.prayer_hours;
create policy "public read hours"
on public.prayer_hours for select
to anon
using (false);

create or replace view public.prayer_hours_total as
select coalesce(sum(hours), 0)::numeric(12,2) as hours
from public.prayer_hours;

grant select on public.prayer_hours_total to anon;
